Repository userbotindo/Anjani, pull requests merged in 2023-05, with the labels that each got.

#289 feat(welcome): Add media welcomes
  anjani/language/en.yml
  anjani/plugins/welcome.py
Labels: feature: enhancement, scope: plugin

#295 change some text ID lang.
  anjani/language/id.yml
Labels: scope: locale

#298 build(Dockerfile): bump to python 3.10
  Dockerfile
Labels: type: maintenance

#299 feat(canonical): add health-check web service
  anjani/plugins/canonical.py
  docker-compose.yml
  entrypoint.sh
Labels: feature: addition

#300 build(Dockerfile): download internal package on layer
  Dockerfile
  docker-compose.yml
  entrypoint.sh
Labels: ENV Changes, scope: internal
